---
- name: Stop httpd (Apache) on Ubuntu
  hosts: ourServer
  become: yes
  vars:
    serviceName: "apache2"
  tasks:
    - name: Stop Apache
      service:
        name: "{{ serviceName }}"
        state: stopped
        enabled: yes

