---
- name: Gather and display system information
  hosts: all
  gather_facts: yes
  tasks:
    - name: Display hostname
      debug:
        msg: "Hostname: {{ ansible_hostname }}"

    - name: Display OS version
      debug:
        msg: "OS: {{ ansible_distribution }} {{ ansible_distribution_version }}"

    - name: Display CPU information
      debug:
        msg: "CPU: {{ ansible_processor[1] }} ({{ ansible_processor_vcpus }} vCPUs)"

    - name: Display total memory
      debug:
        msg: "Memory: {{ ansible_memtotal_mb }} MB"

    - name: Display disk usage
      command: df -h /
      register: disk_usage

    - name: Show disk usage
      debug:
        msg: "{{ disk_usage.stdout_lines }}"

    - name: Display system uptime
      command: uptime -p
      register: system_uptime

    - name: Show uptime
      debug:
        msg: "{{ system_uptime.stdout }}"

