---
- name: Remove a file from a remote server
  hosts: vms
  gather_facts: false
  tasks:
    - name: Delete the file from the remote server
      file:
        path: ~/copyFile.yml.{{ lookup('env', 'USER') }}
        state: absent
